
name: Zip Release
on: 
  push:
    tags:
      - '*'
  workflow_dispatch:
    tags:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
    contents: write
    steps:
      - uses: actions/checkout@master
      - name: Zip Release
        uses: TheDoctor0/zip-release@main
        with:
          filename: 'marlin.zip'
          exclusions: '*.github* *.vscode*'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "marlin.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
