
name: Zip Release
on:
  push:
    branches: [ "2.1.x" ]
  pull_request:
    branches: [ "2.1.x" ]

    workflow_dispatch: ziprelease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Zip Release
        uses: TheDoctor0/zip-release@main
        with:
          filename: 'marlin.zip'
          exclusions: '.github .vscode'

