
name: Zip Release
on:
  push:
    branches: [ "2.1.x" ]
    tags:
    - '*'
  pull_request:
    branches: [ "2.1.x" ]
    tags:
    - '*'
  workflow_dispatch:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master

      - name: Zip Release
        uses: TheDoctor0/zip-release@main
        with:
          filename: 'marlin.zip'
          exclusions: '.github .vscode'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "marlin.zip"
          token: ${{ secrets.GITHUB_TOKEN }}  
