
name: Zip Release
on: 
  push:
    tags:
      - '*'
  workflow_dispatch:
    tags:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Release
        uses: TheDoctor0/zip-release@main
        with:
          filename: 'marlin.zip'
          exclusions: '*.github* *.vscode*'
      - uses: actions/upload-artifact@v1
        with:
          name: marlin-zip
          path: ${{ github.workspace }}/marlin.zip
